#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("app.android.Resource", IsApplication=true)]

namespace app.android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::app.core.Resource.String.ApplicationName = global::app.android.Resource.String.ApplicationName;
			global::app.core.Resource.String.Hello = global::app.android.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int logo72x72 = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050002
			public const int artcileListView = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int articleItemDesc = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int articleItemTitle = 2131034112;
			
			// aapt resource value: 0x7f050006
			public const int editText1 = 2131034118;
			
			// aapt resource value: 0x7f050009
			public const int fbCheck = 2131034121;
			
			// aapt resource value: 0x7f05000b
			public const int linkedInChk = 2131034123;
			
			// aapt resource value: 0x7f050007
			public const int messageTxt = 2131034119;
			
			// aapt resource value: 0x7f05000c
			public const int publishBtn = 2131034124;
			
			// aapt resource value: 0x7f050003
			public const int saveContent = 2131034115;
			
			// aapt resource value: 0x7f050005
			public const int textView1 = 2131034117;
			
			// aapt resource value: 0x7f05000a
			public const int twitterChk = 2131034122;
			
			// aapt resource value: 0x7f050004
			public const int viewArticles = 2131034116;
			
			// aapt resource value: 0x7f050008
			public const int wpChk = 2131034120;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ArticleItem = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ArticleList = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int SaveArticle = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040007
			public const int SaveArticleFB = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int SaveArticleLI = 2130968584;
			
			// aapt resource value: 0x7f040002
			public const int SaveArticleScreen = 2130968578;
			
			// aapt resource value: 0x7f04000a
			public const int SaveArticleStore = 2130968586;
			
			// aapt resource value: 0x7f040009
			public const int SaveArticleTW = 2130968585;
			
			// aapt resource value: 0x7f040003
			public const int SaveArticleTitle = 2130968579;
			
			// aapt resource value: 0x7f040005
			public const int SaveArticleTxt = 2130968581;
			
			// aapt resource value: 0x7f040004
			public const int SaveArticleUrlTxt = 2130968580;
			
			// aapt resource value: 0x7f040006
			public const int SaveArticleWP = 2130968582;
			
			// aapt resource value: 0x7f04000b
			public const int ViewArticleButton = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int ViewArticleTitle = 2130968588;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
